# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LoginScreen' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LoginScreen
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'

  target 'LoginScreenTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LoginScreenUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
